# These are supported funding model platforms


github: abhisheknaiidu
patreon: abhisheknaidu
open_collective: quarantine-days
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with up to 4 custom sponsorship URL
